import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { tb_reclamacao_cliente_por_if} from "@prisma/client";
import { getResposta } from '@/services/perguntas_v1';

const inter = Inter({ subsets: ['latin'] })


export async function getStaticProps(){
	const data = await getResposta(1);
	console.log(data);
	return {
		props: {
			initialData: data
		}
	}
}

export default function Home({initialData}: {initialData:tb_reclamacao_cliente_por_if[]}) {
	const [data, setData] =  useState<tb_reclamacao_cliente_por_if[]>(initialData);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {data.map((c: any, i: number) => (
					<div key={i}>
						<h4>{c.nm_instituicao_financeira}</h4>
					</div>
				))}
      </main>
    </>
  )
}
